### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [VegaBobo/DSU-Sideloader#1]
Thanks for making this app available! May I ask what license you're putting it under? Without any license, it's "all rights reserved" and thus not "truly free" :wink:

**Comment by VegaBobo** [comment]
Thank you for your attention, i've updated license right now, it is Apache 2.0 :)

**Comment by IzzySoft** [comment]
Thanks a lot! Will be [reflected here](https://apt.izzysoft.de/fdroid/index/apk/vegabobo.dsusideloader) with the next sync tomorrow around 19:00 UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there :smiley:

Oh: And should you want to have something adjusted (description, screenshots), or want to have that in your repo here using [Fastlane structures](https://gitlab.com/snippets/1895688) so you can easily adjust it yourself, just let me know. I can provide you with the initial Fastlane structure via a PR, or perform updates locally at my end.
