### ISSUE TITLE
UserData partition size not working...

### ISSUE THREAD

**Issue by YSpoof** [VegaBobo/DSU-Sideloader#10]
Downloaded latest AOSP from PHH: [AOSP 12.0 v402](https://github.com/phhusson/treble_experimentations/releases/tag/v402)

Packed it as a GZIP on PC, got the size for it on PC as well ( du -b system.img )

Selected the GZIP on the app, infromed the system bytes size, selected userdata do be 16GB ( I've set as default using the app settings )

Flashed, all went good, but when I rebooted to the DSU, the whole system has only 8GB avaliable

Btw, I'm brazilian.

**Comment by VegaBobo** [comment]
Fixed, if you want a build with that, pick this one
[app-debug.zip](https://github.com/VegaBobo/DSU-Sideloader/files/8102788/app-debug.zip)
