### ISSUE TITLE
Magisk Installation

### ISSUE THREAD

**Issue by TheArtyomMDev** [VegaBobo/DSU-Sideloader#11]
Hello, how could I flash Magisk on it?
After booting to recovery I flash same with main rom version (24.1) but after installation Magisk manager shows its not installed (on DSU rom)
Or how could I edit system files from DSU rom?

**Comment by VegaBobo** [comment]
By now, Magisk does not support DSU, when you start your device on DSU with a Magisk patched boot.img, Magisk will detect it, and will skip its own loading.
Also, DSU Sideloader only helps users installing GSIs via DSU, after installation is done, there is nothing our app can do, everything will follow the same as Android DSU feature.

**Comment by TheArtyomMDev** [comment]
So could I patch boot.img with Magisk and start DSU rom with this boot.img?
If so, how exactly could I do it?

**Comment by VegaBobo** [comment]
You're already doing that, since DSU will boot using your device current boot.img (that is rooted, because you have flashed Magisk), however, by now, Magisk does not support DSU, so, it shows "not installed", we hope it gets supported in future.

**Comment by TheArtyomMDev** [comment]
Ah, okay. Big thanks for explaining!
I thought that DSU is same with A/B slots so it will use it own boot.img 
Anyway waiting for fix from Magisk dev
