### ISSUE TITLE
Cant install multiple images 

### ISSUE THREAD

**Issue by Asleeppp** [VegaBobo/DSU-Sideloader#119]
I can't seem to install multiple images I've tried with system and product including both in a zip installation doesn't go to preparation just goes to preparing userdata and then fails immediately even though dsu sideloader states that it can support installing multiple partitions

**Comment by VegaBobo** [comment]
Sorry for late answer, kinda busy :\\\, Anyway it should support installation of DSU Packages, do image files inside the zip renamed according to its partition?
eg. if you want to flash "system" and "product" partition, zip file should hold two images, system image, as "system.img" and product, as "product.img".
Check this: https://source.android.com/docs/core/ota/dynamic-system-updates#making-dsu-package
Also, are you using "builtin installer"? if so, disable it
If errors are still happening, can you send me the logs from app crash?

**Comment by Asleeppp** [comment]
> Sorry for late answer, kinda busy :\, Anyway it should support installation of DSU Packages, do image files inside the zip renamed according to its partition? eg. if you want to flash "system" and "product" partition, zip file should hold two images, system image, as "system.img" and product, as "product.img". Check this: https://source.android.com/docs/core/ota/dynamic-system-updates#making-dsu-package Also, are you using "builtin installer"? if so, disable it If errors are still happening, can you send me the logs from app crash?

Thanks yeah it turns out that the issue was built in installer got it working afterwords
