### ISSUE TITLE
Adding support for rom Installing

### ISSUE THREAD

**Issue by TheArtyomMDev** [VegaBobo/DSU-Sideloader#12]
Sometimes I have ROMs in .zip which includes partitions in .dat.br:
rom.zip:
- META-INF
- system.new.dat.br
- system.patch.dat
- system.transfer.list
- vendor.new.dat.br
- vendor.patch.dat
- vendor.transfer.list
- product.new.dat.br
- ...
It will be great to add converting this roms to GSIs to make them able installing in DSU

**Comment by crazo7924** [comment]
That's not how things work... 🤦
