### ISSUE TITLE
Signed Google Gsi's?

### ISSUE THREAD

**Issue by dtingley11** [VegaBobo/DSU-Sideloader#123]
Hi! Thank you for all of your hard work on this! I just noticed that google gsis have a vbmeta that also come with them. Is there any way we can implement those the same way the official dsu loader does so that we can use signed gsi's on locked bootloaders?

Thank you for all your work on this!

**Comment by VegaBobo** [comment]
Thanks for your recognition!
In your case, check this: 
https://source.android.com/docs/core/ota/dynamic-system-updates
"Verify boot" and "OEM-signed DSU" sections should cover what you need, you might be also interested in "DSU JSON descriptor" if you want to get some a more vanilla approach with DSU Loader, good luck!

**Comment by Manu99it** [comment]
@VegaBobo so we can't use this app to flash google signed GSIs on Pixel devices with locked bootloader, right?

**Comment by VegaBobo** [comment]
I think you can, not tried, but if you install images signed by your OEM, it should work on locked bootloader.
