### ISSUE TITLE
Installation failed : unknow error

### ISSUE THREAD

**Issue by Dead8d** [VegaBobo/DSU-Sideloader#124]
Hi 
I get this problem everytime i install a gsi 

I tried an offical gsi from google and didnt work another gsi but got the same result

Im sure my phone supports dsu loader and supports this gsi 

As i tried it on another phone  that has the same model 
(Oppo A93)
[logs (2).txt](https://github.com/VegaBobo/DSU-Sideloader/files/12602634/logs.2.txt)

**Comment by VegaBobo** [comment]
According to your logs, put GSI file outside workspace_dsuhelper folder, that folder is cleaned upon installation, try putting that file in other location, like Downloads folder, or inside internal storage, it should fix.
