### ISSUE TITLE
No issues!!!!

### ISSUE THREAD

**Issue by FxtremeX** [VegaBobo/DSU-Sideloader#125]
Just wanted to give you proper recognition.  This worked flawlessly on a Celero 5G (codename:  Jupiter).  I wanted to run my android 13 GSI by crDroid on it first before I did anything and I've got to tell you, you are elite.  Thank you so much!!!!!!!

**Comment by VegaBobo** [comment]
Thanks for your recognition and attention, thanks 👍👍
