### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by l3rick** [VegaBobo/DSU-Sideloader#130]
![Screenshot_2023-09-27-13-20-07-864_vegabobo dsusideloader](https://github.com/VegaBobo/DSU-Sideloader/assets/81870900/b4235284-42d6-41bf-b809-2da3caef5acf)
I get this error while I have 40gb of memory left..is there a way to fix it?

**Comment by VegaBobo** [comment]
You can ignore this message and try installing, it may work if you're running Android 13+
To ignore this message, you can, well, just free up some internal storage space, anyway, that is not a error, just a warning.
