### ISSUE TITLE
how to remove 'old' System

### ISSUE THREAD

**Issue by LeOS-GSI** [VegaBobo/DSU-Sideloader#139]
I have forgotten to remove the existing DSU system, before installing a new one. How can I remove the old system/userdata ?

It seems, that I'm now not able to install a new system via sideloader :/

**Comment by VegaBobo** [comment]
If you already have a DSU installation present, installing other images via DSU will discard old installation (that is the default behavior, in case you haven't changed any configuration related to dsu slots, which aren't supported by our app yet), so i think the old installation is already deleted by the time you tried to install other images.

When not using built in installer option, basically once Dynamic System Updates starts image installation, it will call remove(), which will purge existing installation (if exists).
AOSP reference: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/packages/DynamicSystemInstallationService/src/com/android/dynsystem/InstallationAsyncTask.java;l=248;drc=d4035b6eb1192f71af7adae47bf17d22c7356fa1

If you're using built in installer, our app doesn't allow you to install images when you have a existing DSU installation, our app checks it before doing any operation related to installation.
Our app reference: https://github.com/VegaBobo/DSU-Sideloader/blob/master/app/src/main/java/vegabobo/dsusideloader/installer/root/DSUInstaller.kt#L226

No clue, but i think the old installation isn't the problem you're experiencing, but if you still believe on it, there is a lot of ways to discard a existing DSU installation:
- Discard taping "Discard" on "Dynamic System Updates" notification
- If you're rooted, open DSU Sideloader, it should show you a card to do operations with installed DSU, which includes discard installed DSU.
- Android has a built in CLI tool to do some operations, the "gsi_tool" command, you can use it over adb shell, or on rooted devices, using a terminal emulator app, to discard a installation, you can use "gsi_tool wipe", i highly recommend using "gsi_tool -h" to get some help about this tool, may be useful.

As last resort, if you still think you have leftovers, you can check the size of /data/gsi/dsu, if that folder is empty, then you're likely without any installation present.

Anyway, i still think  the old installation isn't the problem you're experiencing, so, what do you mean by not able to install? you got some error or anything related to it?

**Comment by LeOS-GSI** [comment]
thx for explanation. I'm sad, my device is bricked (broken screen), so I can't write you more details. :/
