### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by T0mValdomero** [VegaBobo/DSU-Sideloader#140]
I was having several errors when installing, problems with little space (I have more than 60 GB free) I have tried different methods, including the magisk module, old versions of the app and activating or deactivating some options in the settings, here I leave the log.  My device is a moto g 100, running stock Android 12 
![Screenshot_20231029-230919](https://github.com/VegaBobo/DSU-Sideloader/assets/149346486/8dbfb860-42fc-4382-b5d9-66862f3e8ba6)

**Comment by T0mValdomero** [comment]
![Screenshot_20231030-003117](https://github.com/VegaBobo/DSU-Sideloader/assets/149346486/41838de4-57bf-4684-9465-587487a9071e)

**Comment by VegaBobo** [comment]
First image says it cannot find "/data/gsi/dsu" folder, did you have deleted it? if so, create that folder again using any file manager that supports root, if that folder exists, then you must install DSU Sideloader module, it should fix this problem (maybe that error is related to selinux denials, which are addressed by DSU Sideloader module).
Second error, as you can see, says you don't have free storage, DSU installation requires at least 40% of free storage in some Android versions, free up some space, set a lower userdata value, you must have at least 40% of free storage, regardless, that is a limitation imposed by some Android versions.
