### ISSUE TITLE
Unable to boot to DSU

### ISSUE THREAD

**Issue by Goo-aw233** [VegaBobo/DSU-Sideloader#142]
Using the Android 13 GSI image provided by Google (Android 12,11,10 as well), when rebooting to the DSU system after a successful installation, it will go to the bootloader

When the power button is pressed during the Start option, it will automatically reboot to the current system

**Comment by Goo-aw233** [comment]
[logs.txt](https://github.com/VegaBobo/DSU-Sideloader/files/13315075/logs.txt)
I'm not sure if this log works, but I'm still uploading it
:(

**Comment by archerallstars** [comment]
I also have this issue with Google GSI Android 14. It won't boot to GSI no matter what, even with verity disabled. Lenovo Tab P11 TB-J606L here.

**Comment by VegaBobo** [comment]
You cannot boot GSIs that are older than your vndk version, that isn't supported, it will fail even if you try flashing image directly into system partition.
It seems you have a Pixel 5, running Android 14, i guess your VNDK version is 34 (API level 34, which is Android 14), you can only boot GSIs that are equal or higher to your vndk version, which means you can only boot GSIs running Android 14 or higher, due your vndk implementation.

**Comment by hamadzidani** [comment]
@VegaBobo why he cannot install lower Android versions? In my case I was having Android 14 and now installed Android 13.
2- How do you get the logs?
