### ISSUE TITLE
Failed to create partition error in realme 9 4g

### ISSUE THREAD

**Issue by DarkBird10020** [VegaBobo/DSU-Sideloader#144]
I don't why I cannot install gsi in my mobile using dsu sideloader with Root and also without root.Does anyone know how to resolve this issue

**Comment by VegaBobo** [comment]
Can you send installation logs? with that we can analyze this problem further

**Comment by DarkBird10020** [comment]
I don't know how to know or capture installation logs file Can you give me some instruction. But when I am installing latest version dsu sideloader it is force stop.When i resolve it says failed to create partition

**Comment by VegaBobo** [comment]
To obtain logs, you must run the app as root or shizuku operation mode, after that, try to install a image, once installation fails, there is a button called "View logs", tap on it, a popup with logs will be shown, and in that section, there is a button called "Save logs", tap on it, save file anywhere you want, and send that file containing the logs to us, thanks!

**Comment by DarkBird10020** [comment]
Hey my dsu sideloader app is not working now it is crashing after set up after just clicking set up button. I have given it superuser rights still.I think I have flashed dsu in magisk any solution also installed dsu of different versions but after deleting the app and reinstalling the app and also removing the dsu from magisk flash it doesn't work.In other same mobile it is working

**Comment by DarkBird10020** [comment]
I always gave all superuser rights still after crashing it shows denied superuser rights

**Comment by DarkBird10020** [comment]
![Screenshot_2024-02-21-13-26-23-34_9c014b01b516a75953e64717adf03966](https://github.com/VegaBobo/DSU-Sideloader/assets/151629933/959ed301-7f1b-4ad2-aac5-a77baee6f022)
![Screenshot_2024-02-21-13-27-33-18_b783bf344239542886fee7b48fa4b892](https://github.com/VegaBobo/DSU-Sideloader/assets/151629933/7ac79c2f-b357-4c43-85bb-9b9c4915dee6)

**Comment by DarkBird10020** [comment]
![Uploading Screenshot_2024-02-21-13-31-25-18_b783bf344239542886fee7b48fa4b892.jpg…]()

**Comment by DarkBird10020** [comment]
![Screenshot_2024-02-21-13-31-25-18_b783bf344239542886fee7b48fa4b892](https://github.com/VegaBobo/DSU-Sideloader/assets/151629933/794f6a95-6295-404b-bc6d-52582d48fa68)
