### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by BluBerryPlayz** [VegaBobo/DSU-Sideloader#146]
Installation fails every time on Galaxy Tab A 8.0" 2019 (smt295)
I have even tried unmounting the sd card
[logs.txt](https://github.com/VegaBobo/DSU-Sideloader/files/13512355/logs.txt)

**Comment by VegaBobo** [comment]
Your device does implement dynamic partitions, DSU requires that, unfortunately your device is incompatible.
