### ISSUE TITLE
Where userdata stored?

### ISSUE THREAD

**Issue by Levantosa** [VegaBobo/DSU-Sideloader#147]
How to access it from original system?

**Comment by VegaBobo** [comment]
Likely in /data/gsi/dsu, but i don't think it is useful, likely userdata partition is encrypted anyway.

**Comment by Levantosa** [comment]
Could it be decrypted by any means?

**Comment by Levantosa** [comment]
If this is not employed it will be a downside of this app,
Feature requested:
Mount internal storage for both gsi and system a.k.a. cross acces between systems.

**Comment by VegaBobo** [comment]
Well, i think you should be able to run a GSI which doesn't enforce encryption, so you should be able, in theory, to mount DSU installed userdata (system partition is already mountable).
But yea, not supported by this app yet, no clue if that will be a feature.
