### ISSUE TITLE
Restart does not switch to GSI rom

### ISSUE THREAD

**Issue by mcdull** [VegaBobo/DSU-Sideloader#15]
I installed it to Lenovo Xiaoxin PadPro 2021.  Its an Android 11 system with DSU support. 
The default Android 12 GSI runs fine with buildin option.

I installed this app (non root) and installed GSI rom, but upon restart, it just restarted to original rom.  The option is still there at notification bar to ask me to "discard" or "restart".  Tried restart many times, all reboot back to mainos.

**Comment by VegaBobo** [comment]
Maybe avb is preventing device from booting GSI, try flashing disabled vbmeta:

1. Download vbmeta image here: https://developer.android.com/topic/generic-system-image#flash-gsi
2. flash using: fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
3. reboot and test!

Some devices may require you a factory reset after flashing vbmeta (i got this issue with my Moto G30, no clue if it happens in other devices), so, just in case, do some backup before trying.

**Comment by mcdull** [comment]
Thanks for your reply,  it happens on some image only around 80% of the rom has this issue.
but some 20%, like the 
https://github.com/phhusson/treble_experimentations/releases/tag/v410 
which is fine. 

It however, have other issue that the screen is very laggy.
