### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Tanzin01** [VegaBobo/DSU-Sideloader#16]
Logs-
[logs.txt](https://github.com/VegaBobo/DSU-Sideloader/files/8498016/logs.txt)
 
Hope the app grows.

**Comment by VegaBobo** [comment]
You're using Android 10, right?
Android 10 seems to have this bug, fortunately it was fixed on 11, however people running Android 10 seem to be "out of luck".
I tried to fix this issue by building a custom gsid with some patches from Android 11, however, i do not have a Android 10 device to test it :\

Anyway, what Android version you're running? do you have Magisk installed? if so, i can send create a module with a custom gsid binary that may fix your issue (no clue if it will work)

**Comment by Tanzin01** [comment]
yes. It a android 10. I tried using dsu loader from a android 12 gsi. I couldnt get magisk on this pre rooted gsi.....So no magisk.

Appreciate for your asking. But dont wanna waste your time since will get a new device soon :)

**Comment by Tanzin01** [comment]
If you are oky with investing your time for a10 devices. I can test things out for!

**Comment by VegaBobo** [comment]
You can try it if you want to: 
https://github.com/VegaBobo/DSU-Sideloader/issues/13#issuecomment-1114341148

**Comment by VegaBobo** [comment]
Ill be closing this as completed, DSU Sideloader v2 includes a optional Magisk module that adds a custom gsid binary, in which, may fix this Android 10 issue, i've tested installation, and seems to be working as expected (i cannot test if installation was really working because the unique device i have to test it, was one with locked bootloader).

**Comment by Tanzin01** [comment]
Took some time for preparation. So late replay...

On a gsi(android10)-
Was stuck on " proccessing user data" step for about 30min without any progress(:bar), then I decided to click the log button. The app crashed.

Will try on stock ROM later

**Comment by Tanzin01** [comment]
![Uploading Screenshot_20221024-203010_Settings.png…]()
