### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by davidabsenta** [VegaBobo/DSU-Sideloader#18]
You need to have custom recovery for it to work. I have a pixel 4xl and I tried many gsi but none of them work all at the moment of restarting they take me to the recovery stock

**Comment by VegaBobo** [comment]
You don't need a custom recovery.
Your bootloader is unlocked? thats required to boot most GSIs out there.
If you're with unlocked bootloader, then, probably vbmeta is preventing device from booting GSI, you can try flashing disabled vbmeta, i've made some quick instructions here: https://github.com/VegaBobo/DSU-Sideloader/issues/15#issuecomment-1094633182
