### ISSUE TITLE
"Installed failed" on Pixel 3 (blueline) unlocked bootloader

### ISSUE THREAD

**Issue by litbeep** [VegaBobo/DSU-Sideloader#20]
Hi, I can't seem to install any GSIs with this app; I have the latest version of Magisk, my bootloader is unlocked, and I have tried the stock ROM as well as various different custom ROMs but they all fail to install. I even flashed vbmeta per this comment https://github.com/VegaBobo/DSU-Sideloader/issues/18#issuecomment-1146674953 and did a factory reset but the issue persists. Attached is the most recent logfile. 

Any assistance would be appreciated!
 

[logs.txt](https://github.com/VegaBobo/DSU-Sideloader/files/8854737/logs.txt)
.

**Comment by VegaBobo** [comment]
I think i know that problem can be, but first, lets diagnose:
1. Download any terminal emulator app
2. Run `ls /sys/fs/` (if it returns a error, or "permission denied", try the same, but as root, running `su` command)
3. Send me the output of this command

**Comment by litbeep** [comment]
Alright, here's what I got.

`$ su
:/data/data/com.termux/files/home # ls /sys/fs/
bpf ecryptfs f2fs_dev pstore
cgroup ext4 fuse selinux
:/data/data/com.termux/files/home #`

**Comment by VegaBobo** [comment]
Your kernel is registering f2fs as f2fs_dev, gsid expects it to be f2fs, causing this error:
`E gsid    : read failed: /sys/fs/f2fs/dm-4/features: No such file or directory`

There some ways to fix this:
- You can modify libfiemap, to use correct path given by your kernel (probably [here](https://cs.android.com/android/platform/superproject/+/master:system/core/fs_mgr/libfiemap/utility.cpp;l=113?q=%2Fsys%2Ffs&ss=android%2Fplatform%2Fsuperproject:system%2Fcore%2Ffs_mgr%2Flibfiemap%2F))
- You can build your device kernel, but modifying `kernel_folder/fs/f2fs/sysfs.c`, replace f2fs_dev with f2fs

If you don't know about building, you can try to use custom kernel, maybe some of them are registering f2fs as expected.
On future, i plan to release some custom gsid binaries with workarounds to those kind of issues, no clue when that is gonna to happen.

**Comment by litbeep** [comment]
I am actually already using a custom kernel, currently I have Kirisakura installed. But the issue happened with the stock and Pixel Experience kernel, whatever that uses. Not keen on building my own solution so I suppose I'll leave it there for now.

**Comment by VegaBobo** [comment]
Ill be closing this as completed, DSU Sideloader v2 includes a optional Magisk module that adds a custom gsid binary, in which, adds a new check to f2fs_dev before failing, i've tested installation, and seems to be working as expected.
Feel free to reopen or create a new issue in a future problem.
