### ISSUE TITLE
Need to manually create folder `Download/dsu` otherwise NPE

### ISSUE THREAD

**Issue by yujincheng08** [VegaBobo/DSU-Sideloader#21]

**Comment by VegaBobo** [comment]
I think this may fix your issue: https://github.com/VegaBobo/DSU-Sideloader/commit/99a4b35968e42442606af8287a0490ebff600fb3
When selected folder is not available (eg. user deleted it using file manager), folder cannot be reached, and probably causing NPE, now, when selected folder doesn't exists, it will prompts user to select a new folder again (like when user first opens app).

If you want to test it:
https://github.com/VegaBobo/DSU-Sideloader/actions/runs/2471020395
