### ISSUE TITLE
Dynamic System Updates (Install Failed) on my infinix hot 11s

### ISSUE THREAD

**Issue by infinixuer9323232** [VegaBobo/DSU-Sideloader#23]
Hello I am new with this, I just used your sideloader to test some gsi, but when the download of DSU start the progress move in the middle and turns into "Installation failed" is there ways to fix this?

**Comment by VegaBobo** [comment]
What Android version you're running?
Also, if possible, can you provide me logs?

if you don't know how to do so, check "Diagnosing errors", here: 
https://github.com/VegaBobo/DSU-Sideloader/releases/tag/1.02)

**Comment by saebaryo-xyz** [comment]
Hi,

I am also getting exactly the same issue.
Using a Samsung M51 with android 11, unlocked bootloader and with Magisk 25.2.

I have 55GB free space.

Logs attached.
Thanks!
[logs.txt](https://github.com/VegaBobo/DSU-Sideloader/files/9613882/logs.txt)

**Comment by VegaBobo** [comment]
DSU Sideloader v2 includes a installation diagnostics, try to install a GSI using DSU Sideloader v2, if issue persist, feel free to open a new issue with logs (which can be obtained within app).
