### ISSUE TITLE
Cannot boot into Dynamic System On redmi k50

### ISSUE THREAD

**Issue by Ichigokano** [VegaBobo/DSU-Sideloader#24]
Canstall,but can't enter

**Comment by Ichigokano** [comment]
https://drive.google.com/file/d/1-6YXG7FC8CKk9evgw8b8Df6o70DGj62f/view?usp=drivesdk

**Comment by VegaBobo** [comment]
You can try this: https://github.com/VegaBobo/DSU-Sideloader/issues/15#issuecomment-1094633182

**Comment by Ichigokano** [comment]
> Your bootloader is unlocked? If so, you can try this: [#15 (comment)](https://github.com/VegaBobo/DSU-Sideloader/issues/15#issuecomment-1094633182)

yes,and I had flashed vbmeta without avb.I will try phh aosp then.

**Comment by Ichigokano** [comment]
> Your bootloader is unlocked? If so, you can try this: [#15 (comment)](https://github.com/VegaBobo/DSU-Sideloader/issues/15#issuecomment-1094633182)

aosp Booted,but screen flash😂
