### ISSUE TITLE
“Your Device is Corrupted and Cannot be Trusted”

### ISSUE THREAD

**Issue by nxexcelsior** [VegaBobo/DSU-Sideloader#26]
Under certain circumstances, loading a DSU through this app on a Google Pixel 6a device may trigger a bug that persists through factory reset. 

The device will display “Your Device is corrupted and cannot be trusted”. before every boot. The message persisted after performing a restore from factory image (preserving user data). 

The likely cause was LSposed, Magisk, and Zygote. However, in my testing, Magisk and Zygote resulted in a reboot back to the original OS without the error. 

I was still able to successfully boot a Google Android 13 GSI and my normal OS even after the error occurred.

It may be the VNDK-Lite Phh GSI floss 64 ab build from June 2022 that triggered the flag. 

https://forum.xda-developers.com/t/new-solution-without-wiping-pixel-6-pro-irregular-error-message-your-device-is-corrupt-it-cant-be-trusted-and-may-not-work-properly.4400091/

The solution (found on XDA was to flashing an older boot.img to reset the corruption flag. 

The screen went away after flashing the stock boot from Android 13 because it was the only other system image available with a different security month. (July 2022 vs August 2022). 

However using this app to install a DSU seems to have triggered the corruption flag and likely bug.

**Comment by VegaBobo** [comment]
I think this issue is likely due AVB, try flashing disabled vbmeta: https://developer.android.com/topic/generic-system-image#flash-gsi
