### ISSUE TITLE
DSU-Sideloader Crash

### ISSUE THREAD

**Issue by Dachoni03** [VegaBobo/DSU-Sideloader#32]
Hello! When I try to Install some Android 13 GSI from Nippon GSI. The App it's Crashing. I'm using MIUI 12.5.12 and my Device is Redmi 9T - Chime

**Comment by VegaBobo** [comment]
Try DSU Sideloader v2, lots of issues have been fixed in this version, if problem persists, feel free to open a issue with logs.
