### ISSUE TITLE
Userdata only with 8gb

### ISSUE THREAD

**Issue by RyanKF** [VegaBobo/DSU-Sideloader#33]
My problem with the app is the following, regardless of the value I put in "userdata" it always stays at 8gb, what intrigues me is that in the "Install" script, it has the value I had previously set (32gb).
![Screenshot_20220918-225542_Configurações](https://user-images.githubusercontent.com/87386314/190938837-d35f7e87-085c-427f-9de7-d2e1aa150f66.png)

[install.txt](https://github.com/VegaBobo/DSU-Sideloader/files/9595757/install.txt)

sorry for my horrible english, portuguese is my native language

**Comment by VegaBobo** [comment]
Fixed in DSU Sideloader v2.
