### ISSUE TITLE
Possible answer to failed issue

### ISSUE THREAD

**Issue by Lctsolutions** [VegaBobo/DSU-Sideloader#38]
I have a theory that it is failing for people because one of two things. Including myself because it worked before but not now.
1. Inactive slot is not clear and we need instructions on how to clear the slot if it is not clear already such as after an update install that never got discarded
2. Active slot is not changing for some reason where it was changing successfully before.

In the first case, we need information about HOW to clear the inactive slot. Second can be resolved by switching active manually upon reboot

**Comment by VegaBobo** [comment]
Installation process automatically clean a older installation if a installation is started [as you can see here](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r8:frameworks/base/packages/DynamicSystemInstallationService/src/com/android/dynsystem/InstallationAsyncTask.java;l=248), is also possible to delete installed dynamic system by running: "gsi_tool wipe".
You can force device to boot into installed DSU by using this command "gsi_tool enable -s" (-s, --single-boot).

Anyway, give a try to the DSU Sideloader v2, it may fix some of those issues.
If they persist, feel free to reopen or open a new issue.
