### ISSUE TITLE
Is it possible to run a gsi image with an android version that's lower to the android version on my device?

### ISSUE THREAD

**Issue by yejunjie10311031** [VegaBobo/DSU-Sideloader#40]
I have unlocked bootloader and disabled vbmeta.
My device's android version is 12.1. Now I need to try a gsi which android version is lower than 12.1. But I can't boot to it after finishing installing the gsi,it will go into the bootloader.
Is there any way to solve the problem?

**Comment by VegaBobo** [comment]
That does not seem to be supported by Android, according to documentation ([here](https://developer.android.com/topic/generic-system-image#device-compliance)):
 - If device fully supports VNDK = Can boot any GSI that is newer from your device OS.
 - If device does not fully supports VNDK = Can boot only GSIs running same Android version as your device OS.

Anyway, if your device has a outdated firmware running a old Android version, you can try to downgrade, maybe old firmware contains old VNDK implementation, that may let you boot some older GSIs.
