### ISSUE TITLE
It cannot be installed on MIUI13

### ISSUE THREAD

**Issue by Haipeng-Huang** [VegaBobo/DSU-Sideloader#5]
It cannot be installed on MIUI13
I tried adb and the problem remained the sam

This is the log
[Log.txt](https://github.com/VegaBobo/DSU-Sideloader/files/8041416/Log.txt)

**Comment by VegaBobo** [comment]
Can you try this version? if same error happen, please give me logs again 

[app-debug.zip](https://github.com/VegaBobo/DSU-Sideloader/files/8065436/app-debug.zip)
