### ISSUE TITLE
I has some questions!

### ISSUE THREAD

**Issue by binhvo7794** [VegaBobo/DSU-Sideloader#52]
Please make a magisk module, increase the userdata size!!, My phone can only set 18G maxium, I am running Android 11

**Comment by LandChit** [comment]
> Please make a magisk module, increase the userdata size!!, My phone can only set 18G maxium, I am running Android 11

https://github.com/VegaBobo/DSU-Sideloader/releases/download/2.01/module_DSU_Sideloader-gsid.zip

**Comment by VegaBobo** [comment]
Free up some storage, then you should be able to increase userdata size, unfortunatelly, some Android versions restricts DSU installation when there less than 40% of free storage, throwing a error on installation, the checks added on DSU Sideloader are made to prevent this behavior, you can install the module with gsid that contains a custom gsid binary that reduces this limitation to 40% to 20%, you can also trick the module props to reduce even further on app UI, if you're willing to do so, do it by your own and keep in mind that you may have errors.
