### ISSUE TITLE
Will it support a DSU package that contains a system.img, a product.img and more?

### ISSUE THREAD

**Issue by AngelaCooljx** [VegaBobo/DSU-Sideloader#6]
As described in the [android docs](https://source.android.com/devices/tech/ota/dynamic-system-updates):
dsu.zip {
    - system.img
    - product.img
}

**Comment by AngelaCooljx** [comment]
Use adb command
`adb shell setprop persist.sys.fflag.override.settings_dynamic_system 1 && adb shell setprop persist.sys.fflag.override.settings_dynamic_system.list https://angelacooljx.github.io/dsu-test/gsi-src-local.json`
and put dsu.zip on /sdcard
```
dsu.zip {
- system.img
- product.img
- system_ext.img
}
```

It successfully booted on my device (Redmi K30 Ultra mt6885 with PixelExperience 12 self-build).

**Comment by VegaBobo** [comment]
Added initial support for DSU packages, if you want to test it
[app-debug.zip](https://github.com/VegaBobo/DSU-Sideloader/files/8065257/app-debug.zip)

**Comment by AngelaCooljx** [comment]
I will test it later, thanks!!!
