### ISSUE TITLE
Stuck at Installation

### ISSUE THREAD

**Issue by willie666687** [VegaBobo/DSU-Sideloader#63]
![IMG_20230312_220558_524](https://user-images.githubusercontent.com/89621369/224550079-ebcfe9c9-7246-4ed7-bbb1-0cd4edd4a10f.jpg)
It stucks at this moment
The "Try again" doesn't do anything
And my operation mode is root/system
Device: RMX2202 Android 13

**Comment by VegaBobo** [comment]
Install and open any terminal emulator app (like Termux, Material Terminal or many others..), after that:
1. run `su` and give root permission
2. run `setprop persist.sys.fflag.override.settings_dynamic_system true`
3. run `pm install-existing com.android.dynsystem`
4. run `pm enable com.android.dynsystem`

Once done, try to use DSU Sideloader again.

**Comment by VegaBobo** [comment]
DSU Sideloader v2.03 always enforce "settings_dynamic_system" when possible, stucking in installation prompt may be related to this, ill be closing this issue as completed, if problem persists, feel free to open issue again.
