### ISSUE TITLE
Magisk support

### ISSUE THREAD

**Issue by asislife20** [VegaBobo/DSU-Sideloader#64]
Hi, I was able to get the side loader working on my ZTE Nubia Red Magic 5G. I am wondering how to root the side loaded gsi. I tried patching my stock boot.img, but as soon as the gsi boots it goes to the lock screen and then black. Restoring the stock boot.img allows it to boot again. Am I missing something? Is this even possible?

**Comment by VegaBobo** [comment]
Your boot.img is shared between original OS and DSU, which means if your original OS is rooted with Magisk, then DSU should be also, try to use other GSI to test if same behavior occurs.

**Comment by asislife20** [comment]
Every GSI that I have tried does the same thing. If I don't have my boot.img patched with magisk it boots fine. If I try to patch it, it boots to lock screen and goes black, but you can hear notifications and such. I ended up using a GSI with root built in and stock boot.img and it works great! Thank you for all the work you've put into this, It really is a great app.
