### ISSUE TITLE
Not Booting to DSU 

### ISSUE THREAD

**Issue by Reyanejaz123** [VegaBobo/DSU-Sideloader#65]
Hello I have an infinix  zero x neo running Android 11 non rooted   when I click on restart  my phone restarts But Boot me Back in you my original Os not the Dsu os

**Comment by VegaBobo** [comment]
Your device's bootloader is unlocked? if yes, then try to disable boot verification by flashing vbmeta, in most devices you should follow these steps: https://github.com/VegaBobo/DSU-Sideloader/issues/15#issuecomment-1094633182
** i cannot guarantee if those steps will work in your device, i have no clue about your device, neither this brand. 

Unlocking bootloader is a requirement, if you aren't unlocked yet, unlock it before trying to boot GSIs.

**Comment by Reyanejaz123** [comment]
Thank you
