### ISSUE TITLE
Notification doesn't comes after running adb command

### ISSUE THREAD

**Issue by Creation2283** [VegaBobo/DSU-Sideloader#7]
I downloaded the GSI file and normally followed the instructions. App said to run the adb command to start installation I ran the command, A popup appeared in my phone for asking the password, I entered the password, some commands ran and nothing happened!

Device Poco C3 (MIUI 12.0.16.0) Based on Android 10

Thanks in Advance

**Comment by Creation2283** [comment]
I also tried the release version but the app crashes

**Comment by VegaBobo** [comment]
Can you test with latest version?
https://github.com/VegaBobo/DSU-Sideloader/releases/tag/1.02

If same thing happen, enable "Debug installation" on app preferences, install any gsi you like, run adb command, enter your password on DSU dialog, and wait some seconds, after that, cancel command execution on terminal
Now you will probably have a file called "logcat_dsu.txt" into your internal storage, pick this file and send here, so we can diagnose it further.

**Comment by Creation2283** [comment]
Thanks for your reply, 
I come to know that my device only has 'a' partion,
My device doesn't support dynamic partitions😅😞.

Sorry for distributing you.

**Comment by Creation2283** [comment]
Is there any method to install it in A only devices?
