### ISSUE TITLE
Installation hangs up and does nothing

### ISSUE THREAD

**Issue by asrieldashie** [VegaBobo/DSU-Sideloader#73]
Using gsid module.
The installation does nothing after I authenticated.
Sideloader and whole Android system does not froze up or anything like that, just a notification that stuck on "Install in process".
[Logcat](https://pastebin.com/tbeVJpfb) 

The gsid module was working on my rom (Crdroid) before March security patch update, unsure if it's related but I'll leave this info as well.
![Screenshot_20230405-180624_DSU Sideloader_1](https://user-images.githubusercontent.com/24969756/230051235-31da580d-3369-44b0-9f42-4cb215c7890d.png)
![Screenshot_20230405-180717_DSU Sideloader_1](https://user-images.githubusercontent.com/24969756/230051242-f5a53506-e1bf-4aff-94e8-df37e1705bbe.png)

**Comment by VegaBobo** [comment]
Installation proceeds without module? if so, it seems like replaced gsid binary from module hangs gsiservice, likely due some incompatibility, you can try to install the module again, if it doesn't work, then its likely a binary issue, and further analysis is required, i don't tested the custom gsid binary after march update, it may be broken with this new build, ill test once i get time.

**Comment by asrieldashie** [comment]
Installation never worked without the module before and after March update, it just instantly fail to install.

I'll try reinstalling the module and see.

**Comment by asrieldashie** [comment]
I just downgraded the version of Magisk (Delta) I was using and the module seem to be working again. 
The latest [fdac22ba build](https://github.com/HuskyDG/magisk-files/releases/tag/fdac22ba-delta) seemed to broke the gsid module.

**Comment by VegaBobo** [comment]
Can you test the latest Magisk version with this module?
[dsu_sideloader-module-gsid.zip](https://github.com/VegaBobo/DSU-Sideloader/files/11175877/dsu_sideloader-module-gsid.zip)
