### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by brunoxd-crypto** [VegaBobo/DSU-Sideloader#82]
the gsi boots but after 5 minutes the gsi dies and sends instantly to the stock system Samsung A03 Core (Gsi Android 13) (Stock System Android 12) Fix?

**Comment by VegaBobo** [comment]
Likely to be a GSI problem, not DSU, i recommend flashing GSI permanently and check if this problem occur, if you're sure that is a problem that happen only in GSI installed via DSU, feel free to reopen this issue.
