### ISSUE TITLE
Installing vendor and other partitions

### ISSUE THREAD

**Issue by TheArtyomMDev** [VegaBobo/DSU-Sideloader#9]
Hello, I can install system.img but I don't know how to install vendor for this system.img
Do u know how to do it or  can I implement it in the future?
Thanks for your help!
And which vendor is using right now?

**Comment by VegaBobo** [comment]
Create a DSU package: https://source.android.com/devices/tech/ota/dynamic-system-updates#making-dsu-package

Pick vendor.img, system.img (and other partitions if you want), compact them into a ZIP file, and install it using DSU Sideloader.

Keep in mind that some partitions are unsupported by DSU: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/packages/DynamicSystemInstallationService/src/com/android/dynsystem/InstallationAsyncTask.java;l=56
