### ISSUE TITLE
Update and change user data limitation

### ISSUE THREAD

**Issue by SunixDev** [VegaBobo/DSU-Sideloader#91]
Hello, i have a 128gb device and i can allocate only 34go max and i still have place on my device
It would be cool to remove this limitation 
i would like to permanent boot gsi on my device how did you make this work ? i cant flash system img, i have a super partition
could this be possible by editig a file ?

thanks

**Comment by VegaBobo** [comment]
That limitation was added due some Android versions requiring at least 40% of free storage when installing a DSU (not a app limitation, but Android limitation), you can still remove this limitation from app by enabling developer options (go to about section and tap multiple times in app icon, a toast indicating that developer options have been enabled will be shown), after that, you can remove storage check, keep in mind that it will only remove app UI limitations.
You can make installed DSU boot persistent by enabling sticky mode:
https://github.com/VegaBobo/DSU-Sideloader#how-to-enable-sticky-mode
Anyway, if you only want to use a GSI as main OS, you should install the GSI directly into system partition, sticky mode will only enforce installed DSU to boot, your main OS will still persist on device storage.
