### ISSUE TITLE
I can't discard DSU after I discard from system notification

### ISSUE THREAD

**Issue by alexchiu100014** [VegaBobo/DSU-Sideloader#94]
I discard DSU using DSU notification,then I open DSU Sideloader,found out that image didn't got wiped.

My phone now think that I have installed DSU,discard button is not working,even in Sideloader and gsi_tool command

Shell respond : ServiceManager W 05-20 21:21:14 22668 22668 Waited one second for gsiservice (is service started? are binder threads started and available?)

**Comment by alexchiu100014** [comment]
![Screenshot_20230520-212745_DSU_Sideloader.png](https://github.com/VegaBobo/DSU-Sideloader/assets/48598830/0cd9caf9-6c8a-4282-b43b-2d0016cb49e4)

**Comment by alexchiu100014** [comment]
Well...everything back to normal after I uninstall it from magisk.
Is this a bug or my problem?

**Comment by VegaBobo** [comment]
What Magisk version you're using? can you check if this behavior happen with Magisk 26.1?
Anyway, if module containing custom gsid cause this behavior, the one without it should not have this issue.

**Comment by alexchiu100014** [comment]
> What Magisk version you're using? can you check if this behavior happen with Magisk 26.1?
> Anyway, if module containing custom gsid cause this behavior, the one without it should not have this issue.

I'm using Magisk Delta 25210 rn.
HuskyDG said that update to 26 is coming. And sorry,I can't switch version (or branch) due to functions compatibility issue between Original and Delta (MagiskHide).I will try the one without custom gsid on 25210 first.
