### ISSUE TITLE
Erro ao executar comando no adb

### ISSUE THREAD

**Issue by jorgemaico7** [VegaBobo/DSU-Sideloader#95]
Estou fazendo o procedimento em um aparelho sem acesso root e estou usando o adb no computador, ao rodar o comando sugerido pelo aplicativo obtenho o seguibte erro: sh: /storage/emulated/0/Android/data/vegabobo.dsusideloader/files/install: Permission denied
Estou no Android 11

O que pode ser?

**Comment by VegaBobo** [comment]
Tente utilizar essa versão: 
https://github.com/VegaBobo/DSU-Sideloader/releases/tag/2.01
Talvez funcione, creio eu que deve funcionar, se não funcionar, você pode tentar outros modos de operação do app, com root é bem provavel que você não vai ter esse problema.
