### ISSUE TITLE
The DSU system card has turned on. May I ask how to switch to the main system? Thank you

### ISSUE THREAD

**Issue by xiang473535976** [VegaBobo/DSU-Sideloader#97]
When entering the sticky command adb shell gsi_ Tool enable, the DSU system card is turned on, with TWRP and computer. Can you please tell me how to switch to the main system? Thank you

**Comment by VegaBobo** [comment]
Replace "enable" with "disable", run "adb shell gsi_tool disable" main OS should be booted on next reboot.
